### ISSUE TITLE
M> Translate style_guide_assets/README.md to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/Members#287]
**Completed:** 100%

**Tasks:**
- [x] Create the file [README_GR.md](https://github.com/rchain/Members/blob/master/style_guide_assets/README_GR.md)
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Greek

**Collaborators Work:**
- @ICA3DaR5: 100%
- @zero-andreou: 0%
- @thiefinshadows: 0%

**Suggested Budget:** $5

**Comment by ICA3DaR5** [comment]
This has been completed as well.

**Comment by BelovedAquila** [comment]
@ICA3DaR5 I don't know if you observed this issue  #288 is duplicated? Or should there be a reason for that which we don't understand?

**Comment by kitblake** [comment]
@ICA3DaR5 We don't know yet if everything in style_guide_assets will go into production. Before doing any more translating let's wait on movement.

**Comment by ICA3DaR5** [comment]
@kitblake Alright. No problem :)

**Comment by ICA3DaR5** [comment]
@BelovedAquila Sure, you are right. I just thought it would be better to create an issue on a per file basis.
