### ISSUE TITLE
M> Translate style_guide_assets/presentations/README.md to Greek 

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/Members#288]
**Completed:** 100%

**Tasks:**
- [x] Create the file [README_GR.md](https://github.com/rchain/Members/blob/master/style_guide_assets/presentations/README_GR.md)
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Greek

**Collaborators Work:**
- @ICA3DaR5: 100%
- @zero-andreou: 0%
- @thiefinshadows: 0%

**Suggested Budget:** $10

**Comment by ICA3DaR5** [comment]
This has been completed too!
