### ISSUE TITLE
M> Translate projects/dictionary.md to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/Members#339]
**Completed:** 0%

**Tasks:**
- [x] Create the file [dictionary_GR.md](https://github.com/rchain/Members/blob/master/projects/dictionary_GR.md)
- [ ] Translate the content
- [ ] Check the spelling
- [ ] Review each other's work
- [ ] Have it reviewed by others with knowledge of English and Greek

**Collaborators Work:**
- @ICA3DaR5: 0%
- @zero-andreou: 0%
- @thiefinshadows: 0%

**Suggested Budget:** $1000

**Comment by dckc** [comment]
I recommend against investing in dictionary.md. See also #88, #105 .

**Comment by ICA3DaR5** [comment]
So you say, I shouldn't translate this file?

**Comment by dckc** [comment]
That is my advice, yes.

**Comment by ICA3DaR5** [comment]
Okay then! 👍
