### ISSUE TITLE
M>Translation of the "RChain Vision" video to Greek & timing for the English transcript

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/Members#363]
The RChain Vision video: https://youtu.be/Qftq9S34xgg

**Completed:** 100%

**Tasks:**
- [x] Download the video
- [x] Create timings for the English transcript
- [x] Create a Greek transcript
- [x] Check the spelling
- [x] Review each other's work
- [x] View video with the English transcript and review
- [x] View video with the Greek transcript and review
- [x] Have the English transcript reviewed by others with knowledge of English
- [x] Have the Greek transcript reviewed by others with knowledge of Greek
- [x] Upload the English (translated) transcript, [here](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)
- [x] Upload the Greek (translated) transcript, [here](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

**Collaborators Work:**
- @ICA3DaR5: 40%
- @zero-andreou: 30%
- @thiefinshadows: 30%

**Suggested Budget**: $500

English Transcript (Timed) .srt File: https://drive.google.com/open?id=11UDjYcavvenHuZ1SX9KH2_qpLC2G0ieh
Greek Transcript .srt File: https://drive.google.com/open?id=1fOcl9_FiYfNGoQyY2iedK8OyU7UpGkcV

**Comment by Ojimadu** [comment]
An English transcript of this already exists, so we don't reinvent the wheel.

**Comment by ICA3DaR5** [comment]
Okay, do you have a link to the transcript? I don't seem to find one :/

**Comment by ICA3DaR5** [comment]
@Ojimadu I don't see anything on the video's page: https://www.youtube.com/watch?v=Qftq9S34xgg

**Comment by ICA3DaR5** [comment]
So is there an English transcript for the **[RChain Vision](https://www.youtube.com/watch?v=Qftq9S34xgg)** video?

**Comment by Tonyprisca13** [comment]
I just watched the video there is a transcript on the video link.

**Comment by ICA3DaR5** [comment]
@lapin7 What should I do?

**Comment by ICA3DaR5** [comment]
@lapin7 Who should I contact to upload both of these captions to YouTube?

**Comment by lapin7** [comment]
@Mervyn853 knows how to get the .srt on the youtube video.

**Comment by ICA3DaR5** [comment]
@Mervyn853 Could you help me with that?
